### NP1. Create a NumPy array and convert it to a Pandas Series.

In [ ]:
import numpy as np
import pandas as pd
arr = np.array([33,22,25,65,85,69,77])
df = pd.Series(arr,index=['a','b','c','d','e','f','g'],name = "Number")
print(df)

a    33
b    22
c    25
d    65
e    85
f    69
g    77
Name: Number, dtype: int64

### NP2. Convert a 2D NumPy array to a Pandas DataFrame.

In [ ]:
arr2 = np.array([[10,20,30,40],
                 [50,60,70,80],
                 [90,100,110,120]])
df2 = pd.DataFrame(arr2,columns=["Col 1","Col 2","Col 3","Col 4"],index = ["Row 1","Row 2","Row 3"])
print(df2)

       Col 1  Col 2  Col 3  Col 4
Row 1     10     20     30     40
Row 2     50     60     70     80
Row 3     90    100    110    120

### NP3. Generate a random dataset using NumPy and store it in a DataFrame.

In [ ]:
np.random.seed(42)
random_data = np.random.randn(5,3)
df_random = pd.DataFrame(random_data,columns=["Col 1","Col 2","Col 3"])
print(df_random)

      Col 1     Col 2     Col 3
0  0.496714 -0.138264  0.647689
1  1.523030 -0.234153 -0.234137
2  1.579213  0.767435 -0.469474
3  0.542560 -0.463418 -0.465730
4  0.241962 -1.913280 -1.724918

In [ ]:
r_d = np.random.randint(69, 96, 10)
df.r_d = pd.DataFrame(r_d)
print(df.r_d)

    0
0  69
1  84
2  91
3  91
4  92
5  73
6  71
7  80
8  76
9  90

### NP4. Perform element-wise operations using NumPy and Pandas.

In [ ]:
df_random["Col 1 squared"] = np.square(df_random["Col 1"])
print(df_random[['Col 1','Col 1 squared']])

      Col 1  Col 1 squared
0  0.246725       0.060873
1  2.319620       5.380637
2  2.493913       6.219603
3  0.294371       0.086655
4  0.058546       0.003428

### NP5. Apply `np.mean` on DataFrame columns.

In [ ]:
meean = np.mean(df_random["Col 2"])
print(meean)

-0.39633617684237443

In [ ]:
meaan = np.mean(df_random['Col 2'].values)    # fatest execution
print(meaan)

-0.39633617684237443

### NP6. Replace values using `np.where`.

In [ ]:
data = {'Scores' : [21,55,45,69,80]}
df = pd.DataFrame(data)
df["Scores"] = np.where(df["Scores"] > 45, "High", "Low")
print(df)

  Scores
0    Low
1   High
2    Low
3   High
4   High

### NP7. Apply logarithmic transformation using `np.log`.

In [ ]:
data = {"Values" : [0,4,-9,16,25]}
df = pd.DataFrame(data)
df['Values'] = np.log(df['Values'])
print(df)

     Values
0      -inf
1  1.386294
2       NaN
3  2.772589
4  3.218876

/usr/local/lib/python3.12/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.12/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

### NP8. Apply square root transformation using `np.sqrt`.

In [ ]:
data = {"Values" : [100,64,36,16,9,4,1]}
df = pd.DataFrame(data)
df['Values'] = np.sqrt(df['Values'])
print(df)

   Values
0    10.0
1     8.0
2     6.0
3     4.0
4     3.0
5     2.0
6     1.0

### NP9. Use NumPy functions inside `apply()`.

In [ ]:
df["Values"].apply(lambda x: np.log(x))

0    2.302585
1    2.079442
2    1.791759
3    1.386294
4    1.098612
5    0.693147
6    0.000000
Name: Values, dtype: float64

### NP10. Perform broadcasting in a DataFrame using NumPy.

In [ ]:
weights_array = np.array([0.2, 0.3, 0.5, 0.6, 0.1, 0.8, 0.4])
df["Values"].values @ weights_array

np.float64(12.100000000000001)

## 🔹 NP11–NP20: Data Filtering, Transformation & Statistics

### NP11. Filter DataFrame rows using a NumPy boolean mask.

In [ ]:
threshold = 5.0
df["mask"] = np.array(df['Values'] > threshold)
df['mask']

0     True
1     True
2     True
3    False
4    False
5    False
6    False
Name: mask, dtype: bool

### NP12. Count non-zero values in a column using NumPy.

In [ ]:
np.count_nonzero(df['Values'].values)

7

In [ ]:
np.count_nonzero(df['Values'].values != 0)

7

### NP13. Find unique values using `np.unique`.

In [ ]:
np.unique(df['Values'])

array([ 1.,  2.,  3.,  4.,  6.,  8., 10.])

In [ ]:
np.unique(df['Values'],return_counts=True)

(array([  1,   4,   9,  16,  36,  64, 100]), array([1, 1, 1, 1, 1, 1, 1]))

### NP14. Flatten DataFrame values to a 1D NumPy array.

In [ ]:
data = {"Values" : [100,64,36,16,9,4,1],
        "value" : [1,2,3,4,6,8,10]}
df = pd.DataFrame(data)
df.values.flatten()

array([100,   1,  64,   2,  36,   3,  16,   4,   9,   6,   4,   8,   1,
        10])

### NP15. Reshape a NumPy array before creating a DataFrame.

In [ ]:
arr = np.arange(1,25).reshape(6,4)
pd.DataFrame(arr,columns=["Col 1","Col 2","Col 3","Col 4"])

   Col 1  Col 2  Col 3  Col 4
0      1      2      3      4
1      5      6      7      8
2      9     10     11     12
3     13     14     15     16
4     17     18     19     20
5     21     22     23     24

### NP16. Perform matrix multiplication using `np.dot`.

In [ ]:
A = np.array([[1,2,3]])
B = np.array([[4],
              [5],
              [6]])

mat = np.dot(A,B)
print(mat)

[[32]]

### NP17. Normalize data using NumPy (Min-Max scaling).

In [ ]:
arr = df['Values'].values
arr = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print(arr)

[1.         0.63636364 0.35353535 0.15151515 0.08080808 0.03030303
 0.        ]

### NP18. Standardize data using Z-score with NumPy.

In [ ]:
z = (arr - np.mean(arr,axis = 0)) / np.std(arr,axis=0)
print(z)

[ 1.96307635  0.91053328  0.09188868 -0.49285747 -0.69751862 -0.84370515
 -0.93141708]

### NP19. Clip values using `np.clip`.

In [ ]:
np.clip(df["Values"].values,a_min=0,a_max=200)

array([100,  64,  36,  16,   9,   4,   1])

### NP20. Handle missing values using NumPy.

In [ ]:
data = {'Values': [10.0, np.nan, 20.0, 30.0, np.nan, 40.0]}
df = pd.DataFrame(data)
arr = df['Values'].values
np.isnan(arr)
mean = np.nanmean(arr)
arr[np.isnan(arr)] = mean
print(arr)
df

[10. 25. 20. 30. 25. 40.]

   Values
0    10.0
1    25.0
2    20.0
3    30.0
4    25.0
5    40.0

## 🔹 NP21–NP30: Performance, Sorting & Statistical Analysis

### NP21. Compare NumPy vs Pandas performance on a large array.
💡 **Hint:** Use `time.time()` before and after each operation. Apply the same computation (`arr * 2 + 1`) to a raw NumPy array and a Pandas Series. NumPy is typically faster on pure numeric operations.

In [ ]:
import numpy as np
import pandas as pd
import time

size = 10_000_000
raw_arr = np.random.rand(size)
df = pd.Series(raw_arr)

#Numpy
start_time = time.time()
numpy_res = raw_arr * 2 + 1
end_time = time.time()
numpy_time = end_time - start_time
print("Numpy execution",numpy_time,"sec")

#Pandas
start_timep = time.time()
pandas_res = df * 2 + 1
end_timep = time.time()
pandas_time = end_timep - start_timep
print("Pandas execution",pandas_time,"sec")

speed = pandas_time / numpy_time
print("Numpy is",speed,"times faster than Pandas")

Numpy execution 0.038030147552490234 sec
Pandas execution 0.1071007251739502 sec
Numpy is 2.816205880509059 times faster than Pandas

### NP22. Calculate cumulative sum using NumPy.
> 💡 **Hint:** `np.cumsum(df["col"].values)` — assign back: `df["cum_col"] = np.cumsum(df["col"])`.

In [ ]:
data = {'Values': [10, 69, 20, 30, 50, 40]}
df = pd.DataFrame(data)
df["cum_col"] = np.cumsum(df["Values"])
df

   Values  cum_col
0    10.0     10.0
1    69.0     79.0
2    20.0     99.0
3    30.0    129.0
4    50.0    179.0
5    40.0    219.0

### NP23. Use `np.argmax` and `np.argmin`.
> 💡 **Hint:** `np.argmax(df["col"].values)` returns the **integer position** of the maximum. Use `df.iloc[idx]` or `df.loc[idx]` to retrieve the full row.

In [ ]:
data = { "col" : [15,42,8,99,35]}
df = pd.DataFrame(data,index = ['row 1','row 2','row 3','row 4','row 5'])

#index positions of max and min values
max_idx = np.argmax(df["col"].values)
min_idx = np.argmin(df['col'].values)

#Extract the full rows using .iloc
print(df.iloc[max_idx])
print(df.iloc[min_idx])

col    99
Name: row 4, dtype: int64
col    8
Name: row 3, dtype: int64

### NP24. Sort values using NumPy `np.argsort`.
> 💡 **Hint:** `sorted_idx = np.argsort(df["col"].values)` gives indices that would sort the array. Use `df.iloc[sorted_idx]` to reorder the DataFrame.

In [2]:
import pandas as pd
import numpy as np
data = {'soda' : [100,24,13,64,95,66]}
df = pd.DataFrame(data)
sorted_idx = np.argsort(df["soda"].values)
df.iloc[sorted_idx]

   soda
2    13
1    24
3    64
5    66
4    95
0   100

### NP25. Compute correlation using `np.corrcoef`.
> 💡 **Hint:** `np.corrcoef([df["col1"].values, df["col2"].values])` returns a 2×2 correlation matrix. Wrap in a DataFrame for readability. Compare with `df.corr()`.

In [5]:
data = {
    "col1": [90, 45, 69, 85, 20],
    "col2": [30, 55, 10, 96, 65]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
   col1  col2
0    90    30
1    45    55
2    69    10
3    85    96
4    20    65

In [6]:
matrix = np.corrcoef([df["col1"].values,
                      df["col2"].values])

corr_df = pd.DataFrame(matrix, columns=["col1", "col2"], index=["col1", "col2"])
print("NumPy Correlation Matrix (Wrapped in DataFrame):")
print(corr_df)

print("\nPandas Built-in Correlation:")
print(df.corr())

NumPy Correlation Matrix (Wrapped in DataFrame):
          col1      col2
col1  1.000000 -0.128511
col2 -0.128511  1.000000

Pandas Built-in Correlation:
          col1      col2
col1  1.000000 -0.128511
col2 -0.128511  1.000000

### NP26. Detect NaN values using NumPy.
> 💡 **Hint:** `np.isnan(arr)` returns a boolean array. Count NaN with `np.isnan(arr).sum()`. Compare with `pd.isnull(series)`.

In [7]:
data = {
    "col1": [90, 45, np.nan, 85, 20]
}
df = pd.DataFrame(data)
arr = df["col1"].values
print(np.isnan(arr))
print(np.isnan(arr).sum())
print(pd.isnull(df["col1"]).sum())

[False False  True False False]
1
1

### NP27. Create boolean masks using NumPy.
> 💡 **Hint:** `mask = (np.array(df["col1"]) > 80) & (np.array(df["col2"]) < 40)` — use `df[mask]` to filter.

In [10]:
data = {
    "col1": [90, 45, 69, 85, 20],
    "col2": [30, 55, 10, 96, 65]
}
df = pd.DataFrame(data)
mask = (np.array(df["col1"]) > 80) & (np.array(df["col2"]) < 40)
print(df[mask])

   col1  col2
0    90    30

### NP28. Apply logical operations (`np.logical_and`, `np.logical_or`, `np.logical_not`).
> 💡 **Hint:** `np.logical_and(cond1, cond2)` is equivalent to `cond1 & cond2`. These functions work on NumPy arrays; convert Series with `.values` first.

In [16]:
arr1 = np.array(df['col1'])
arr2 = np.array(df['col2'])
logi = np.logical_and(arr1 > 50, arr2 < 70)
loor = np.logical_or(arr1 > 50, arr2 < 70)
lonot = np.logical_not(arr1 > 50)
print(df[logi])
print("-"*25)
print(df[loor])
print("-"*25)
print(df[lonot])

   col1  col2
0    90    30
2    69    10
-------------------------
   col1  col2
0    90    30
1    45    55
2    69    10
3    85    96
4    20    65
-------------------------
   col1  col2
1    45    55
4    20    65

### NP29. Apply `np.select` for multi-condition assignment.
> 💡 **Hint:** `df["Grade"] = np.select([df["Score"] >= 90, df["Score"] >= 75], ["A","B"], default="C")` — conditions are checked in order; the first match wins.

In [17]:
data = {'Scores' : [21,55,45,69,80,99,96]}
df = pd.DataFrame(data)
df["Grade"] = np.select([df["Scores"] >= 90, df["Scores"] >= 75], ["A","B"], default="C")
df

   Scores Grade
0      21     C
1      55     C
2      45     C
3      69     C
4      80     B
5      99     A
6      96     A

### NP30. Multiply DataFrame columns element-wise using NumPy.
> 💡 **Hint:** `np.multiply(df["col1"].values, df["col2"].values)` is equivalent to `df["col1"] * df["col2"]` but uses NumPy internally.

In [23]:
data = {
    "col1": [90, 45, 69, 85, 20],
    "col2": [30, 55, 10, 96, 65]
}
df = pd.DataFrame(data)
multi = np.multiply(df["col1"].values, df["col2"].values)
check = df["col1"] * df["col2"]
print(multi)
df["multiplied_column"] = multi
print("-"*25)
print(check)
df

[2700 2475  690 8160 1300]
-------------------------
0    2700
1    2475
2     690
3    8160
4    1300
dtype: int64

   col1  col2  multiplied_column
0    90    30               2700
1    45    55               2475
2    69    10                690
3    85    96               8160
4    20    65               1300

## 🔹 NP31–NP40: Data Wrangling & Conversion

### NP31. Shuffle dataset rows using NumPy.
> 💡 **Hint:** `shuffled_idx = np.random.permutation(df.index)` creates a random permutation of row indices. Use `df.loc[shuffled_idx].reset_index(drop=True)`.

In [7]:
data = {
    "col": [10, 22, 35, 47, 50, 63, 75, 88, 91, 105]
}
df = pd.DataFrame(data)
shuffled_idx = np.random.permutation(df.index)
print(shuffled_idx)
shuffle_df = df.loc[shuffled_idx].reset_index(drop=True)
print(shuffle_df)

[2 5 4 1 3 7 6 8 9 0]
   col
0   35
1   63
2   50
3   22
4   47
5   88
6   75
7   91
8  105
9   10

### NP32. Sample random rows using NumPy.
> 💡 **Hint:** `sample_idx = np.random.choice(df.index, size=N, replace=False)` — use `df.loc[sample_idx]`. Compare with `df.sample(N)`.

In [6]:
N = 3
sample_idx = np.random.choice(df.index, size=N, replace=False)
print(sample_idx)
print(df.loc[sample_idx])
print(df.sample(N))

[0 4 1]
   soda
0   100
4    95
1    24
   soda
4    95
0   100
5    66

### NP33. Calculate percentiles using NumPy.
> 💡 **Hint:** `np.percentile(df["col"].values, [25, 50, 75])` returns Q1, median, Q3. Use `np.percentile(arr, p)` for any percentile p in [0, 100].

In [11]:
arr = df['col'].values
q1,median,q3 = (np.percentile(arr, [25, 50, 75]))
print("q1",q1)
print("median",median)
print("q3",q3)
#69
p69 = np.percentile(arr, 69)
print(p69)

q1 38.0
median 56.5
q3 84.75
77.72999999999999

### NP34. Calculate variance and standard deviation.
> 💡 **Hint:** `np.var(arr)` and `np.std(arr)` use `ddof=0` (population). Pandas `.var()` and `.std()` use `ddof=1` (sample). Be aware of this difference when comparing results.

In [14]:
arr = df["col1"].values

# 1. NumPy Calculations (Default: Population, ddof=0)
np_var = np.var(arr)
np_std = np.std(arr)

# 2. Pandas Calculations (Default: Sample, ddof=1)
pd_var = df["col1"].var()
pd_std = df["col1"].std()

print(f"NumPy (Population) -> Var: {np_var}, Std: {np_std}")
print(f"Pandas (Sample)     -> Var: {pd_var}, Std: {pd_std}")

# 3. Matching them up by adjusting ddof
print("\n--- Matching the Results ---")
print(f"NumPy with ddof=1 (Sample):     {np.std(arr, ddof=1)}")
print(f"Pandas with ddof=0 (Population): {df['col1'].std(ddof=0)}")

NumPy (Population) -> Var: 200.0, Std: 14.142135623730951
Pandas (Sample)     -> Var: 250.0, Std: 15.811388300841896

--- Matching the Results ---
NumPy with ddof=1 (Sample):     15.811388300841896
Pandas with ddof=0 (Population): 14.142135623730951

In [15]:
#ddof
data = {
    "col1": [10.0, 20.0, 30.0, 40.0, 50.0],
    "col2": [5.0, 15.0, 25.0, 35.0, 45.0]
}
df = pd.DataFrame(data)
# npvar = np.var(df["col1"].values)
# npstd = np.std(df["col1"].values)
arr = df["col1"].values
npvar = np.var(arr)
npstd = np.std(arr)

pdvar = df["col1"].var()
pdstd = df["col1"].std()

print(npvar)
print(npstd)
print("-"*25)
print(pdvar)
print(pdstd)

print("numpy with ddof=1",np.std(arr,ddof=1))
print("pandas with ddof=0",df['col1'].std(ddof=0))

200.0
14.142135623730951
-------------------------
250.0
15.811388300841896
numpy with ddof=1 15.811388300841896
pandas with ddof=0 14.142135623730951

### NP35. Replace a DataFrame column with a NumPy array.
> 💡 **Hint:** `df["col"] = new_numpy_array` — the array length must match the number of rows. NumPy arrays are accepted directly.

In [16]:
new_numpy_array = np.array([1,2,3,4,5])
df["col"] = new_numpy_array
df

   col1  col2  col
0  10.0   5.0    1
1  20.0  15.0    2
2  30.0  25.0    3
3  40.0  35.0    4
4  50.0  45.0    5

### NP36. Convert DataFrame to NumPy using `to_numpy()`.
> 💡 **Hint:** `df[["col1","col2"]].to_numpy()` returns a 2D NumPy array. This is the preferred method over `.values` as it accepts `dtype` and `na_value` parameters.

In [18]:
data = {
    "col1": [10.0, 20.0, 30.0, 40.0, 50.0],
    "col2": [5.0, 15.0, 25.0, 35.0, 45.0]
}
df = pd.DataFrame(data)
arr = df[["col1","col2"]].to_numpy()
print(arr)
print(arr.shape)
# Using advanced parameters like dtype or handling missing values (na_value)
cm = df[["col 1","col 2"]].to_numpy(dtype=np.float32,na_value = -1)
print(cm)

[[10.  5.]
 [20. 15.]
 [30. 25.]
 [40. 35.]
 [50. 45.]]
(5, 2)

KeyError: "None of [Index(['col 1', 'col 2'], dtype='object')] are in the [columns]"

### NP37. Compare `.values` vs `.to_numpy()`.
> 💡 **Hint:** Both return a NumPy array. Key difference: `.to_numpy(dtype=np.float32)` accepts a `dtype` argument for explicit casting. Use `np.array_equal(a, b)` to confirm they produce the same result.

In [19]:
arr_value = df.values
arr_to_numpy = df.to_numpy(dtype= np.float32)
print(arr_value)
print(arr_to_numpy)
print(np.array_equal(arr_value,arr_to_numpy))

[[10.  5.]
 [20. 15.]
 [30. 25.]
 [40. 35.]
 [50. 45.]]
[[10.  5.]
 [20. 15.]
 [30. 25.]
 [40. 35.]
 [50. 45.]]
True

### NP38. Slice a column using NumPy array indexing.
> 💡 **Hint:** Extract with `.values`, then apply NumPy slicing: `arr[::2]` (every other element), `arr[::-1]` (reversed), `arr[[0,3,5]]` (fancy indexing).

In [21]:
arr = df["col1"].values
print(arr)
print(arr[::2])
print(arr[::-1])
print(arr[[0,3,4]])

[10. 20. 30. 40. 50.]
[10. 30. 50.]
[50. 40. 30. 20. 10.]
[10. 40. 50.]

### NP39. Merge NumPy-generated data into a DataFrame.
> 💡 **Hint:** Create two DataFrames from NumPy arrays with a common key column (e.g., `ID`). Use `pd.merge(df1, df2, on="ID", how="outer")`.

In [23]:
d1 = np.array([[101,500],[102,300],[103,400]])
d2 = np.array([[102,750],[103,390],[104,600]])

df1 = pd.DataFrame(d1,columns=["ID","Value"])
df2 = pd.DataFrame(d2,columns=["ID","Quality"])

merged_df = pd.merge(df1,df2,on="ID",how="outer")
merged_df

    ID  Value  Quality
0  101  500.0      NaN
1  102  300.0    750.0
2  103  400.0    390.0
3  104    NaN    600.0

### NP40. Apply rolling computation using NumPy.
> 💡 **Hint:** Use a list comprehension: `[np.mean(arr[max(0,i-w+1):i+1]) for i in range(len(arr))]` to manually compute a rolling mean with window `w`. Compare with `df["col"].rolling(w).mean()`.

In [29]:
arr = np.array([10, 20, 30, 40, 50])
df = pd.DataFrame({"col": arr})
w = 2
rolling_numpy = [np.mean(arr[max(0, i - w + 1) : i + 1]) for i in range(len(arr))]
print("Manual NumPy Rolling Mean:", rolling_numpy)
print("\nPandas Built-in Rolling Mean:")
print(df["col"].rolling(window=w, min_periods=1).mean().tolist())

Manual NumPy Rolling Mean: [np.float64(10.0), np.float64(15.0), np.float64(25.0), np.float64(35.0), np.float64(45.0)]

Pandas Built-in Rolling Mean:
[10.0, 15.0, 25.0, 35.0, 45.0]

In [32]:
arr = np.array([10, 20, 30, 40, 50])
df = pd.DataFrame({"col": arr})
w = 2
rolling_numpy = [np.mean(arr[max(0, i - w + 1) : i + 1]) for i in range(len(arr))]
print(rolling_numpy)
print(df["col"].rolling(w).mean().tolist())

[np.float64(10.0), np.float64(15.0), np.float64(25.0), np.float64(35.0), np.float64(45.0)]
[nan, 15.0, 25.0, 35.0, 45.0]

## 🔹 NP41–NP50: ML-Ready Dataset Preparation

### NP41. Create a synthetic ML dataset using NumPy.
> 💡 **Hint:** Use `np.random.normal`, `np.random.randint`, `np.random.choice` to generate features. Use `np.where` or `np.select` to create a binary/multi-class label column.

In [33]:
np.random.seed(42)
num_samples = 100
feature_age = np.random.normal(loc = 35,scale = 10,size = num_samples)
# loc= 35 means the mean/avg is 35,scale is std
feature_credit_tier = np.random.randint(low = 1,high = 6,size = num_samples)

conditions = [
    (feature_age < 30) & (feature_credit_tier <= 2),
    (feature_age >= 30) & (feature_credit_tier >= 4)
]

choices = [0,2]

target = np.select(conditions,choices,default = 1)

ml_dataset = pd.DataFrame({
    "Age" : feature_age,
    "Credit_Tier" : feature_credit_tier,
    "Target_Class" : target
})

print(ml_dataset.head())

         Age  Credit_Tier  Target_Class
0  39.967142            1             1
1  33.617357            5             2
2  41.476885            1             1
3  50.230299            3             1
4  32.658466            2             1

### NP42. Detect and replace outliers using NumPy.
> 💡 **Hint:** Compute Q1, Q3 with `np.percentile`. Define bounds as `Q1 - 1.5*IQR` and `Q3 + 1.5*IQR`. Use `np.clip(arr, lo, hi)` to replace outliers with boundary values.

In [34]:
data = {
    "col1": [10, 12, 11, 15, 100, 12, 14, 13, 11, 9],
    "col2": [5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
    "category": ["DS", "ML", "AI", "DS", "ML", "AI", "DS", "ML", "AI", "DS"]
}
df = pd.DataFrame(data)

arr = df["col1"].values
q1,q3 = np.percentile(arr,[25,75])

iqr = q3 - q1
lower_bound = q1 - 1.5*iqr
upper_bound = q3 + 1.5*iqr

df["col1_cleaned"] = np.clip(arr,lower_bound,upper_bound)
print("lower",lower_bound)
print("upper",upper_bound)
print(df[['col1','col1_cleaned']])

lower 6.875
upper 17.875
   col1  col1_cleaned
0    10        10.000
1    12        12.000
2    11        11.000
3    15        15.000
4   100        17.875
5    12        12.000
6    14        14.000
7    13        13.000
8    11        11.000
9     9         9.000

### NP43. Scale dataset using NumPy functions.
> 💡 **Hint:** Apply Min-Max or Z-score scaling using NumPy on the `.values` array. Store results as new columns in the DataFrame.

In [35]:
vals = df['col2'].values
df['col2_min_max'] = (vals - np.min(vals)) / (np.max(vals) - np.min(vals))
df['col2_z_score'] = (vals - np.mean(vals)) / np.std(vals)
print(df[['col2','col2_min_max','col2_z_score']])

   col2  col2_min_max  col2_z_score
0     5      0.000000     -1.566699
1    15      0.111111     -1.218544
2    25      0.222222     -0.870388
3    35      0.333333     -0.522233
4    45      0.444444     -0.174078
5    55      0.555556      0.174078
6    65      0.666667      0.522233
7    75      0.777778      0.870388
8    85      0.888889      1.218544
9    95      1.000000      1.566699

### NP44. Engineer new features using NumPy.
> 💡 **Hint:** Create polynomial features (`np.square`, `np.power`), log features (`np.log1p`), interaction features (column1 × column2), and binned features (`np.digitize`).

In [37]:
df["col1_sq"] = np.square(df["col1_cleaned"])
df["col1_log"] = np.log1p(df["col1_cleaned"])
df["interaction"] = df["col1_cleaned"] * df["col2"]
df["binned"] = np.digitize(df["col2"].values,bins = [30,75])
print(df[["col1_sq","col1_log","interaction","binned"]].head())

      col1_sq  col1_log  interaction  binned
0  100.000000  2.397895       50.000       0
1  144.000000  2.564949      180.000       0
2  121.000000  2.484907      275.000       0
3  225.000000  2.772589      525.000       1
4  319.515625  2.937838      804.375       1

### NP45. Use exponential functions (`np.exp`).
> 💡 **Hint:** `np.exp(df["col"])` computes `e^x` for each element. This is the inverse of `np.log`. Useful for reverting log-transformed values.

In [40]:
df["col1_exp"] = np.exp(df["col1"])
print(df[["col1_cleaned","col1_exp","col1_log"]])

   col1_cleaned      col1_exp  col1_log
0        10.000  2.202647e+04  2.397895
1        12.000  1.627548e+05  2.564949
2        11.000  5.987414e+04  2.484907
3        15.000  3.269017e+06  2.772589
4        17.875  2.688117e+43  2.937838
5        12.000  1.627548e+05  2.564949
6        14.000  1.202604e+06  2.708050
7        13.000  4.424134e+05  2.639057
8        11.000  5.987414e+04  2.484907
9         9.000  8.103084e+03  2.302585

### NP46. Compute differences using `np.diff`.
> 💡 **Hint:** `np.diff(df["col"].values)` returns an array of consecutive differences (length = n−1). Prepend `np.nan` and assign back: `df["col_diff"] = np.insert(np.diff(arr), 0, np.nan)`.

In [42]:
arr_diff = df["col1"].values.astype(float)
diffs = np.insert(np.diff(arr_diff),0,np.nan)
df["col1_diff"] = diffs
print(df[["col1","col1_diff"]])

   col1  col1_diff
0    10        NaN
1    12        2.0
2    11       -1.0
3    15        4.0
4   100       85.0
5    12      -88.0
6    14        2.0
7    13       -1.0
8    11       -2.0
9     9       -2.0

### NP47. Apply conditional encoding using NumPy.
> 💡 **Hint:** Use `np.select` with a list of conditions and corresponding integer codes to encode categorical columns numerically. For example: `DS → 0`, `ML → 1`, `AI → 2`.

In [44]:
conditions = [
    df["category"] == "DS",
    df["category"] == "ML",
    df["category"] == "AI"
]
choices = [0,1,2]
df["category_encoded"] = np.select(conditions,choices,default=-1)
print(df[["category","category_encoded"]])

  category  category_encoded
0       DS                 0
1       ML                 1
2       AI                 2
3       DS                 0
4       ML                 1
5       AI                 2
6       DS                 0
7       ML                 1
8       AI                 2
9       DS                 0

### NP48. Build an ML-ready dataset (feature matrix X and label vector y).
> 💡 **Hint:** Select numeric feature columns → call `.to_numpy(dtype=np.float32)` → store as `X`. Create a binary label: `y = (df["col"] >= threshold).astype(int).to_numpy()`. Check shapes with `X.shape` and `y.shape`.

In [47]:
feature_col = ["col1_cleaned","col2_min_max","category_encoded"]
X = df[feature_col].to_numpy(dtype=np.float32)
y = (df["col1_cleaned"] >= 50).astype(int).to_numpy()
print(X.shape)
print(y.shape)
print(X[:3])

(10, 3)
(10,)
[[10.          0.          0.        ]
 [12.          0.11111111  1.        ]
 [11.          0.22222222  2.        ]]

### NP49. Perform a mini data analysis project.
> 💡 **Hint:** Follow these steps: (1) Generate data with NumPy, (2) Store in DataFrame, (3) Clean with Pandas, (4) Engineer features with NumPy, (5) GroupBy analysis, (6) Detect outliers, (7) Export summary.

In [48]:
raw_met = np.random.normal(loc=200,scale=50,size=15)

pro_df = pd.DataFrame({"Revenue" : raw_met})
pro_df["Region"] = np.random.choice(["North","South","East"],size=15)

pro_df["Revenue"] = pro_df["Revenue"].fillna(pro_df["Revenue"].median())

pro_df["Log_Revenue"] = np.log1p(pro_df["Revenue"])

summ = pro_df.groupby("Region")["Revenue"].agg(["mean","std","count"])
print(summ)

q25,q75 = np.percentile(pro_df["Revenue"],[25,75])
pro_df["Is_Outlier"] = ~pro_df["Revenue"].between(q25 - 1.5*(q75-q25),q75 + 1.5*(q75-q25))
print(pro_df[["Revenue","Is_Outlier"]])

pro_df.to_csv("mini_analysis_output.csv", index=False)
print("\nMini analysis pipeline exported successfully.")

              mean        std  count
Region
East    224.226512  43.661547      5
North   188.620245  53.898577      7
South   214.366586  45.113066      3
       Revenue  Is_Outlier
0   252.467370       False
1   266.255283       False
2   236.725053       False
3   152.275137       False
4   162.441029       False
5   143.478597       False
6   238.498868       False
7   263.419476       False
8   221.224312       False
9   247.026779       False
10  156.617946       False
11  207.293093       False
12  131.506447       False
13  161.410963       False
14  243.933677       False

Mini analysis pipeline exported successfully.

### NP50. Build an end-to-end pipeline using NumPy + Pandas.
> 💡 **Hint:** Chain all steps together:  
> 1. `np.random.seed(X)` → generate raw data  
> 2. `np.clip` → clean invalid values  
> 3. `np.log`, `np.square`, `np.where` → feature engineering  
> 4. `df.groupby().agg(...)` → statistical analysis  
> 5. IQR + `np.clip` → outlier removal  
> 6. `df[features].to_numpy(dtype=np.float32)` → ML feature matrix  
> 7. Export with `df.to_csv(...)`

In [51]:
def run_pipeline(seed_value=42):
  np.random.seed(seed_value)
  rows = 200

  raw_data = {
      "Age" : np.random.uniform(low=15 ,high=90,size=rows),
      "Income" : np.random.normal(loc=55000,scale=25000,size=rows),
      "score" : np.random.choice([1,2,3,4],size = rows)
  }
  pp_df = pd.DataFrame(raw_data)

  pp_df["Age"] = np.clip(pp_df["Age"],18,80)

  pp_df["Log_Income"] = np.log1p(np.maximum(0,pp_df["Income"]))
  pp_df["Age_Squared"] = np.square(pp_df["Age"])
  pp_df["High_Earner"] = np.where(pp_df["Income"] > 60000,1,0)

  summ = pp_df.groupby("score")["Age"].agg(["mean","median"])
  print("Pipeline grouped checkpoint",sum)

  in_vals = pp_df["Income"].values
  q1_in, q3_in = np.percentile(in_vals,[25,75])
  iqr_in = q3_in - q1_in
  pp_df["Income_cleaned"] = np.clip(in_vals,q1_in - 1.5 * iqr_in,q3_in + 1.5 * iqr_in)

  ml_features = ["Age","Income_cleaned","Log_Income","Age_Squared","High_Earner"]
  Xmat = pp_df[ml_features].to_numpy(dtype=np.float32)
  print("\nFinal Matrix Export shape",Xmat.shape)

  pp_df.to_csv("final_pipeline_dataset.csv",index=False)
  print("Pipeline process run finished successfully.")

run_pipeline()

Pipeline grouped checkpoint <built-in function sum>

Final Matrix Export shape (200, 5)
Pipeline process run finished successfully.